import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins, Fira_Code } from "next/font/google";
import NxtProvider from "@/Providers/NxtProvider";

// const roboto = Poppins({
//   weight: "400",
//   subsets: ["latin"],
// });
const roboto = Fira_Code({
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/eagle.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel='icon' href='/favicon.ico'/> */}
        <link rel="icon" href="/eagle.jpeg" />
      </head>
      <body className={roboto.className}>
        <NxtProvider>{children}</NxtProvider>
      </body>
    </html>
  );
}
