import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import NxtProvider from "@/Providers/NxtProvider";

const roboto = Poppins({
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NxtProvider>{children}</NxtProvider>
      </body>
    </html>
  );
}
